### PR TITLE
Fix Dialyzer Specs

### PR DESCRIPTION
**Pull request by ulissesalmeida**
My company project is failing with `has no local return`
error. After isolating the problem, the source was
the `Scheduler.get_{next/previous}_run_date`.

The first suspcicious is `get_{next/previous}_run_date` could
raise an explicit exception, but the specs says no.

Also, the private functions are all covered with specs, it's not
necessary. Since you add a spec in a public, and dialyzer
will check the private ones respects the public. I think
these privates specs was misleading Dialyzer.

This fix might not be 100% backward compatible, but it respects more
the documented specs.

Let me know what you think.

### CODE REVIEW

**Comment by maennchen** [comment]
Thanks @ulissesalmeida for the PR.

I'm not sure though that I like all of the changes. The Typespecs on the private functions are actually wanted. If they're wrong, it'd be good to correct them instead.

Why did you replace the `maybe` type?

**Comment by maennchen** [comment]
BTW: `has no local return` says that dialyzer thinks that a function will never return in any case. The `raise` should only trigger that warning if it thinks that this is the only code-path it could take.

We'll also have to remove the breaking change. I'm not planning on doing a major update solely based on this change.

**Comment by maennchen** [comment]
How did you call the library? The following code yields no dialyzer errors:

```elixir
defmodule Test do
  import Crontab.CronExpression

  def test do
    Crontab.Scheduler.get_next_run_date(~e[*]e)
  end

  def test2 do
    for date <- Crontab.Scheduler.get_next_run_dates(~e[*]e) do
      IO.inspect(date)
    end
  end
end
```

**Comment by ulissesalmeida** [comment]
@maennchen I'll give you more details soon.

**Comment by ulissesalmeida** [comment]
Hey sorry for bothering you.

Actually, I think my problem was some weird caching of Dialyzer, I nuked everything and tried again from scratch and worked fine. Then you can ignore this PR 😆 

The problem of `maybe`, in other languages means `just something` or `empty/nil`.
Here, `maybe` usage reminds me of the `either`, for example `either(:ok, :error)`. In erlangs/elixir specs, `either` can be translated to `|`. Then we could write as `:ok | :error`.

Another thing that I didn't like that much was the `any` for error reason. It's too generic, in these functions we know what can be returned(is String.t() or exception.

About the `private` specs, no strong feelings. If you like it, I can put it back.

But actually, there's no bug here. But if you want these improvements, let me know. I can reopen the PR removing the stuff you didn't like it.

**Comment by maennchen** [comment]
@ulissesalmeida No worries, thanks anyways!

You're right about the `maybe` naming. I should probably change it to `result` as well. (Like result in Rust...)

Also, the `any` in the `error` case could be more specific.

I'd be interested in a PR that addresses those two issues.

**Pull request closed without merging**
