### PR TITLE
Adding String.trim to Ecto Type cast()

### PR DESCRIPTION
**Pull request by h4cc**
Fixing https://github.com/jshmrtn/crontab/issues/88

Automatic tests seem to be broken :(

### CODE REVIEW

**Review by maennchen — APPROVED** [review]

**Comment by maennchen** [comment]
@h4cc I fixed the CI. Thanks for the PR :heart:

**Comment by maennchen** [comment]
@h4cc Could you run `mix format`?

**Comment by h4cc** [comment]
> @h4cc Could you run `mix format`?

Done

**Comment by maennchen** [comment]
@h4cc Thanks. Released as `v1.1.11`

**Pull request merged**
